### ISSUE TITLE
Feature Request: Change background color

### ISSUE THREAD

**Issue by RhinoInani** [CoderUni/bottom_bar#1]
Hello,
I love the package and have been using it for a while. But as I am progressing I realized that there is one major issue. There is no way to change the background color. I have tried all known ways to do this with a normal bottom navigation bar, and I still couldn't find one. If someone knows a way to do so please let me know, and if it is not a feature yet, please try to implement it in an upcoming update as it would greatly improve the usability of your package.

Thanks,
Rhino

**Comment by CoderUni** [comment]
Thanks for writing the issue, what do you mean by background color? Is it the background color of each item or background color of the entire bottom bar? You could set the background color of each bottombaritem individually but not yet the entire bottom bar. I'll be adding the feature you requested in a future update.

**Comment by RhinoInani** [comment]
I was talking about the entire background of the bar. It would be a great feature if we could make it a different color to fit/contrast with the rest of the app. Thank you I will be looking forward to an update with this feature.

**Comment by CoderUni** [comment]
Thanks for filing the issue, I've added support for adding a background color in ^1.2.3

**Comment by RhinoInani** [comment]
Thank you so much for the fast response!
