### ISSUE TITLE
Feature Request: Inactive Icon

### ISSUE THREAD

**Issue by RhinoInani** [CoderUni/bottom_bar#3]
Hello,
Sorry for the constant bugging (pun not intended), but is it possible for you to add an inactive icon as a parameter in the BottomBarItem? This would work similarly to the inactive color. 

Right now I am doing something like this manually but would be easier to have it as a parameter.

```
items: <BottomBarItem>[
            BottomBarItem(
              icon: _currentPage == 0
                  ? Icon(Icons.home)
                  : Icon(Icons.home_outlined),
              title: Text("Home"),
              activeColor: Colors.green,
              inactiveColor: Colors.blueGrey[300],
            ),
            BottomBarItem(
              icon: _currentPage == 1
                  ? Icon(Icons.table_chart)
                  : Icon(Icons.table_chart_outlined),
              title: Text("Tables"),
              activeColor: Colors.blueAccent,
              inactiveColor: Colors.blueGrey[300],
            ),
          ],
````

Hope this is a simple feature to add! 

Thanks, 
Rhino

P.S: Sorry for the constant feature requests, just trying to streamline my code and these requests might help other people who use the package in the future. Thanks once again, keep up the great work! :)

**Comment by CoderUni** [comment]
Sorry, just saw this now. I'll work on this on the next version.

**Comment by RhinoInani** [comment]
Thank you so much.
