### ISSUE TITLE
Overflow error

### ISSUE THREAD

**Issue by marc-walton** [CoderUni/bottom_bar#5]
When more than 4 BottomBarItems are used its show renderflex overflow error.

**Comment by CoderUni** [comment]
Thanks for reporting the issue @marc-walton . Could you send a screenshot of what the `BottomBar` with overflow error looks like in your end?

**Comment by CoderUni** [comment]
Closing since there is no response for 4 months.

**Comment by Purus** [comment]
![screenshot](https://user-images.githubusercontent.com/1077735/200583491-b5c6be7b-1734-4ddc-86c5-b6ec8169dd36.png)

I am having the same issue when I use different language. Please consider this.
