### ISSUE TITLE
[Feature Request] Padding Parameter for BottomBar

### ISSUE THREAD

**Issue by ilkanimal** [CoderUni/bottom_bar#6]
Hi, I noticed that the padding value of the BottomBar has increased in the latest version and this caused mismatch in our app's UI. Could you please add padding parameter to the BottomBar widget?
Thanks for your work on this great package.

**Comment by CoderUni** [comment]
Thanks for filing the feature request :) 

`^2.0.1` now has a padding parameter. Have a great day!
